### ISSUE TITLE
Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kjbrum** [ideil/laravel-mix-twig#9]
I'm getting the following error when changing the `output` config setting.

```shell
[webpack-cli] TypeError: Cannot read property 'length' of undefined
    at /Users/kylebrumm/projects/laravel-mix-with-twig/node_modules/laravel-mix-twig/src/index.js:146:55
    at Array.forEach (<anonymous>)
    at makeHtmlConfig (/Users/kylebrumm/projects/laravel-mix-with-twig/node_modules/laravel-mix-twig/src/index.js:138:25)
    at Twig.webpackPlugins (/Users/kylebrumm/projects/laravel-mix-with-twig/node_modules/laravel-mix-twig/src/index.js:165:13)
    at ComponentRegistrar.applyPlugins (/Users/kylebrumm/projects/laravel-mix-with-twig/node_modules/laravel-mix/src/components/ComponentRegistrar.js:203:23)
    at /Users/kylebrumm/projects/laravel-mix-with-twig/node_modules/laravel-mix/src/components/ComponentRegistrar.js:102:50
    at /Users/kylebrumm/projects/laravel-mix-with-twig/node_modules/laravel-mix/src/Dispatcher.js:37:62
    at Array.map (<anonymous>)
    at Dispatcher.fire (/Users/kylebrumm/projects/laravel-mix-with-twig/node_modules/laravel-mix/src/Dispatcher.js:37:47)
    at Mix.dispatch (/Users/kylebrumm/projects/laravel-mix-with-twig/node_modules/laravel-mix/src/Mix.js:240:32)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gsusg** [comment]
It looks more like plugin can't find `*.twig` files based on glob pattern `root + entries`.

**Comment by gsusg** [comment]
One of default configuration setting was missed.
Try to set `replaceOutputPath: ''` or update the plugin with this fix.
